# Generated by Django 4.0.6 on 2022-08-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_person_age_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bmr',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
