# Generated by Django 3.1.4 on 2022-06-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_testqu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestJson',
        ),
        migrations.DeleteModel(
            name='Testqu',
        ),
    ]
