# Generated by Django 3.1.4 on 2022-06-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220629_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriemodel',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
