# Generated by Django 3.1.4 on 2022-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_caloriemodel_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('num', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
