# Generated by Django 3.1.4 on 2022-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriemodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
